### Login Customer
POST http://localhost:5001/api/customers/login
Content-Type: application/json

{
  "email": "janodijayathunga@gmail.com",
  "password": "123456"
}
### Register Customer
GET http://localhost:5001/api/categories/toys-and-electronics
Content-Type: application/json

###GET 
GET http://localhost:5001/api/categories/toys
Content-Type: application/json

